version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_datacloud
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    ports:
      - 3306:3306