version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - node-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_datacloud
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    ports:
      - 3306:3306
  
  app:
    image: jongusjovi/atvfinaldc:0.0.1
    restart: always
    container_name: atvfinaldc
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"

networks:
  node-network: